### PR TITLE
Add presentation for talk on 2017-03-10

### PR DESCRIPTION
**Pull request by 42pre**
In this presentation I try to very quickly (5 slides) explain the differences between using Codepen or Github for FreeCodeCamp.

Topics:

- Codepen or Github (pros and cons, 1 slide)
- Codepen or Github (licensing and code visibility, 1 slide)
- Do I have to use Codepen (for FCC, 1 slide)
- Cool things in Codepen (1 slide)
- Further readings (links, 1 slide)

### CODE REVIEW

**Comment by DDCreationStudios** [comment]
Hi @42pre , 
Is this a proposal for a talk tomorrow? What's about the discussion circle about open source licensing? Do you want to do both? As you can see on the meetup.com page we already have 2 talks and maybe a discussion would be a better fit for tomorrow? 
I assigned @robeerob  and @lukastillmann  to review. 
Also, please propose talks a little bit more in advance, so that we can organize the event better :)

**Comment by robeerob** [comment]
@42pre I remember us talking briefly about a possible lightning talk for this Friday, at the last meetup. And we talked about whether or not FCC members have to submit a codepen link or not. Was the possible lightning talk this talk, or was it a general "licensing"/"licensing on github" talk?

I agree with @DDCreationStudios that we in general want a little bit more notice about new talk proposals, but honestly can't remember if this is the short 5 minute lightning talk we discussed. 

Please clarify, we'll agree on something :)

**Comment by lukastillmann** [comment]
I agree, I like that idea @robeerob

**Comment by 42pre** [comment]
Hi guys. We had said discussion on FCC/Codepen vs Github for submitting the code for the FCC courses, and also what licenses would be applied (by GH and CP). I offered giving a short lightning talk (3-5 slides) on that topic, but obviously did miss at least one step in how talks should be submitted?

I started a pull request yesterday to let you know that the talk would be ready on my side.

I could do the talk as suggested as a discussion starter (tested it out twice, and it took me roughly 5 minutes if I do all 5 slides). If you want to scrap the talk, it would be fine with me too ;).

PS: As there obviously was some miscommunication involved here, let's discuss (and more importantly clarify in writing) the workflow for submitting talks asap, so that I and other newcomers after me don't have to repeat my mistakes ;)?!

**Comment by DDCreationStudios** [comment]
@42pre @robeerob  @lukastillmann 
Ok I understand! So we will use your talk as introduction and framework for our discussion - great idea! I was just confused because of the codepen specifics :) 
And I agree we will set up a workflow for submitting talks 🚀  :) 👍

**Comment by robeerob** [comment]
@42pre thanks for clarifying! As that is settled now, I see no need to scrap the talk, and you did exactly right in pushing your slides here to the repo. The talk proposal/creation workflow your following is perfect, it seems to just have come down to misunderstandings.

See you tomorrow, and looking forward to the lightning-talk and discussion. Thanks a lot for contributing, it means a lot to us organizers, and I know the attendees appreciate it too :100:

**Pull request merged**
