### PR TITLE
Add license #8

### PR DESCRIPTION
**Pull request by DDCreationStudios**
### adding licenses according to issue #8.

- used same structure as orginal freecodecamp (https://github.com/freeCodeCamp/freeCodeCamp)
- did not want to use a copyleft license due to restraints of marketability (verkehrsfreiheit/-fähigkeit)
- divided the licenses between software and all other content
- overall goal was to give as much freedom as possible since it is opensource, but to have at least credit established

### CODE REVIEW

**Comment by robeerob** [comment]
LGTM +1. @42pre, do you want to chime in, in light of your numerous contributions?

Barring any major arguments against, I suggest we just got with this license, which we can always change in the future if the group decides to (but keeping in mind that everything contributed up until a license change will remain under this license).

**Comment by robeerob** [comment]
@DDCreationStudios @lukastillmann I propose we merge this in 24 hours, unless @42pre replies with any objections.

**Comment by DDCreationStudios** [comment]
@robeerob 
I am writing on our contribution file at the moment. I thought of the same thing. Something like a default merge if one admin approves  after 1 week or so. However, now in this case it's not that urgent. Adding an additional file doesn't block further contribution 🚀

**Comment by DDCreationStudios** [comment]
Merged because review timeframe is elapsed.

**Pull request merged**
